In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
games = pd.read_csv ('/content/games.csv')

In [ ]:
games_details = pd.read_csv ('/content/games_details.csv')

In [15]:
players = pd.read_csv ('/content/players.csv')

In [16]:
ranking = pd.read_csv ('/content/ranking.csv')

In [13]:
teams = pd.read_csv ('/content/teams.csv')

In [17]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  object
 1   GAME_ID           26651 non-null  int64
 2   GAME_STATUS_TEXT  26651 non-null  object
 3   HOME_TEAM_ID      26651 non-null  int64
 4   VISITOR_TEAM_ID   26651 non-null  int64
 5   SEASON            26651 non-null  int64
 6   TEAM_ID_home      26651 non-null  int64
 7   PTS_home          26552 non-null  float64
 8   FG_PCT_home       26552 non-null  float64
 9   FT_PCT_home       26552 non-null  float64
 10  FG3_PCT_home      26552 non-null  float64
 11  AST_home          26552 non-null  float64
 12  REB_home          26552 non-null  float64
 13  TEAM_ID_away      26651 non-null  int64
 14  PTS_away          26552 non-null  float64
 15  FG_PCT_away       26552 non-null  float64
 16  FT_PCT_away       26552 non-null  float64
 17  FG3_PCT_away      26552 non-null  float64
 18  AST_away          26552 non-null  float64
 19  REB_away          26552 non-null  float64
 20  HOME_TEAM_WINS    26651 non-null  int64
dtypes: float64(12), int64(7), object(2)
memory usage: 4.3+ MB

In [18]:
games_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668628 entries, 0 to 668627
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            668628 non-null  int64
 1   TEAM_ID            668628 non-null  int64
 2   TEAM_ABBREVIATION  668628 non-null  object
 3   TEAM_CITY          668628 non-null  object
 4   PLAYER_ID          668628 non-null  int64
 5   PLAYER_NAME        668628 non-null  object
 6   NICKNAME           53037 non-null   object
 7   START_POSITION     255765 non-null  object
 8   COMMENT            109689 non-null  object
 9   MIN                558938 non-null  object
 10  FGM                558938 non-null  float64
 11  FGA                558938 non-null  float64
 12  FG_PCT             558938 non-null  float64
 13  FG3M               558938 non-null  float64
 14  FG3A               558938 non-null  float64
 15  FG3_PCT            558938 non-null  float64
 16  FTM                558938 non-null  float64
 17  FTA                558938 non-null  float64
 18  FT_PCT             558938 non-null  float64
 19  OREB               558938 non-null  float64
 20  DREB               558938 non-null  float64
 21  REB                558938 non-null  float64
 22  AST                558938 non-null  float64
 23  STL                558938 non-null  float64
 24  BLK                558938 non-null  float64
 25  TO                 558938 non-null  float64
 26  PF                 558938 non-null  float64
 27  PTS                558938 non-null  float64
 28  PLUS_MINUS         535277 non-null  float64
dtypes: float64(19), int64(3), object(7)
memory usage: 147.9+ MB

In [19]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7228 entries, 0 to 7227
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PLAYER_NAME  7228 non-null   object
 1   TEAM_ID      7228 non-null   int64
 2   PLAYER_ID    7228 non-null   int64
 3   SEASON       7228 non-null   int64
dtypes: int64(3), object(1)
memory usage: 226.0+ KB

In [20]:
ranking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210342 entries, 0 to 210341
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TEAM_ID        210342 non-null  int64
 1   LEAGUE_ID      210342 non-null  int64
 2   SEASON_ID      210342 non-null  int64
 3   STANDINGSDATE  210342 non-null  object
 4   CONFERENCE     210342 non-null  object
 5   TEAM           210342 non-null  object
 6   G              210342 non-null  int64
 7   W              210342 non-null  int64
 8   L              210342 non-null  int64
 9   W_PCT          210342 non-null  float64
 10  HOME_RECORD    210342 non-null  object
 11  ROAD_RECORD    210342 non-null  object
 12  RETURNTOPLAY   3990 non-null    float64
dtypes: float64(2), int64(6), object(5)
memory usage: 20.9+ MB

In [21]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LEAGUE_ID           30 non-null     int64
 1   TEAM_ID             30 non-null     int64
 2   MIN_YEAR            30 non-null     int64
 3   MAX_YEAR            30 non-null     int64
 4   ABBREVIATION        30 non-null     object
 5   NICKNAME            30 non-null     object
 6   YEARFOUNDED         30 non-null     int64
 7   CITY                30 non-null     object
 8   ARENA               30 non-null     object
 9   ARENACAPACITY       26 non-null     float64
 10  OWNER               30 non-null     object
 11  GENERALMANAGER      30 non-null     object
 12  HEADCOACH           30 non-null     object
 13  DLEAGUEAFFILIATION  30 non-null     object
dtypes: float64(1), int64(5), object(8)
memory usage: 3.4+ KB

In [22]:
games.columns = ['Data do Jogo', 'Código do Jogo', 'Status do Jogo', 'Código do Time Casa', 'Código do Time Visitante', 'Temporada', 'Código do Time Mandante', 'Pontos do Mandante', 'Porcentagem de Arremesso do Mandante', 'Porcentagem de Lance Livre do Mandante', 'Porcentagem de Arremesso de 3 do Mandante', 'Assistência do Mandante', 'Rebotes do Mandante', 'Código do Time Visitante', 'Pontos do Visitante', 'Porcentagem de Arremesso do Visitante', 'Porcentagem de Lance Livre do Visitante', 'Porcentagem de Arremesso de 3 do Visitante', 'Assistência do Visitante', 'Rebotes do Visitante', 'Se o time mandante venceu']

In [23]:
games.head (26651)

,Data do Jogo,Código do Jogo,Status do Jogo,Código do Time Casa,Código do Time Visitante,Temporada,Código do Time Mandante,Pontos do Mandante,Porcentagem de Arremesso do Mandante,Porcentagem de Lance Livre do Mandante,...,Assistência do Mandante,Rebotes do Mandante,Código do Time Visitante,Pontos do Visitante,Porcentagem de Arremesso do Visitante,Porcentagem de Lance Livre do Visitante,Porcentagem de Arremesso de 3 do Visitante,Assistência do Visitante,Rebotes do Visitante,Se o time mandante venceu
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26646,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
26647,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
26648,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
26649,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
26650,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [24]:
games_details.columns = ['Código do Jogo', 'Código do Time', 'Abreviação do Time', 'Cidade do Time', 'Código do Jogador', 'Nome do Jogador', 'Jogador', 'Posição', 'Comentário', 'Minutos', 'Arremessos Convertidos', 'Arremessos Tentados', 'Porcentagem de Arremessos Convertidos', 'Três Pontos Convertidos', 'Três Pontos Tentados', 'Porcentagem de Três Pontos Convertidos', 'Lances Livres Convertidos', 'Lances Livres Tentados', 'Porcentagem de Lance Livres Convertidos', 'Rebotes Ofensivos', 'Rebotes Defensivos', 'Rebotes', 'Assistências', 'Roubos', 'Arremessos Bloqueados', 'Turnover', 'Faltas', 'Pontos Feitos', 'Plus-Minus']

In [25]:
games_details.head (668628)

,Código do Jogo,Código do Time,Abreviação do Time,Cidade do Time,Código do Jogador,Nome do Jogador,Jogador,Posição,Comentário,Minutos,...,Rebotes Ofensivos,Rebotes Defensivos,Rebotes,Assistências,Roubos,Arremessos Bloqueados,Turnover,Faltas,Pontos Feitos,Plus-Minus
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668623,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,NaN,19,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
668624,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,NaN,23,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
668625,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,NaN,15,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
668626,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,NaN,19,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
668627,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,NaN,27,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

In [26]:
players.columns = ['Nome do Jogador', 'Código do Time', 'Código do Jogador', 'Temporada']

In [27]:
players.head(7228)

       Nome do Jogador  Código do Time  Código do Jogador  Temporada
0        Royce O'Neale      1610612762            1626220       2019
1     Bojan Bogdanovic      1610612762             202711       2019
2          Rudy Gobert      1610612762             203497       2019
3     Donovan Mitchell      1610612762            1628378       2019
4          Mike Conley      1610612762             201144       2019
...                ...             ...                ...        ...
7223       Lanny Smith      1610612758             201831       2009
7224     Warren Carter      1610612752             201999       2009
7225      Bennet Davis      1610612751             201834       2009
7226    Brian Hamilton      1610612751             201646       2009
7227   Wesley Matthews      1610612762             500032       2009

[7228 rows x 4 columns]

In [28]:
ranking.columns = ['Código do Time', 'Código da Liga', 'Código da Temporada', 'Data do Jogo', 'Conferência', 'Time', 'Partidas Jogadas', 'Partidas Ganhas', 'Partidas Perdidas', 'Porcentagem de Vitórias', 'Jogos em Casa', 'Jogos Fora', 'Retornos']

In [29]:
ranking.head(210342)

,Código do Time,Código da Liga,Código da Temporada,Data do Jogo,Conferência,Time,Partidas Jogadas,Partidas Ganhas,Partidas Perdidas,Porcentagem de Vitórias,Jogos em Casa,Jogos Fora,Retornos
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

In [30]:
teams.columns = ['Código da Liga', 'Código do Time', 'Primeiro Ano no Campeonato', 'Último Ano no Campeonato', 'Abreviação', 'Time', 'Fundação', 'Cidade', 'Arena', 'Capacidade da Arena', 'Dono', 'Responsável', 'Técnico', 'Afiliação']

In [31]:
teams.head (30)

,Código da Liga,Código do Time,Primeiro Ano no Campeonato,Último Ano no Campeonato,Abreviação,Time,Fundação,Cidade,Arena,Capacidade da Arena,Dono,Responsável,Técnico,Afiliação
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends
5,0,1610612743,1976,2019,DEN,Nuggets,1976,Denver,Pepsi Center,19099.0,Stan Kroenke,Tim Connelly,Michael Malone,No Affiliate
6,0,1610612745,1967,2019,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Daryl Morey,Mike D'Antoni,Rio Grande Valley Vipers
7,0,1610612746,1970,2019,LAC,Clippers,1970,Los Angeles,Staples Center,19060.0,Steve Ballmer,Michael Winger,Doc Rivers,Agua Caliente Clippers of Ontario
8,0,1610612747,1948,2019,LAL,Lakers,1948,Los Angeles,Staples Center,19060.0,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel,South Bay Lakers
9,0,1610612748,1988,2019,MIA,Heat,1988,Miami,AmericanAirlines Arena,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
10,0,1610612749,1968,2019,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens & Marc Lasry,Jon Horst,Mike Budenholzer,Wisconsin Herd
11,0,1610612750,1989,2019,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Glen Taylor,Scott Layden,Ryan Saunders,Iowa Wolves
12,0,1610612751,1976,2019,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Kenny Atkinson,Long Island Nets
13,0,1610612752,1946,2019,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Steve Mills,David Fizdale,Westchester Knicks
14,0,1610612753,1989,2019,ORL,Magic,1989,Orlando,Amway Center,0.0,Rick DeVos,John Hammond,Steve Clifford,Lakeland Magic
15,0,1610612754,1976,2019,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Nate McMillan,Fort Wayne Mad Ants
16,0,1610612755,1949,2019,PHI,76ers,1949,Philadelphia,Wells Fargo Center,NaN,Joshua Harris,Elton Brand,Brett Brown,Delaware Blue Coats
17,0,1610612756,1968,2019,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,NaN,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns
18,0,1610612757,1970,2019,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Paul Allen,Neil Olshey,Terry Stotts,No Affiliate
19,0,1610612758,1948,2019,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
20,0,1610612759,1976,2019,SAS,Spurs,1976,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs
21,0,1610612760,1967,2019,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,19163.0,Clay Bennett,Sam Presti,Billy Donovan,Oklahoma City Blue
22,0,1610612761,1995,2019,TOR,Raptors,1995,Toronto,Scotiabank Arena,19800.0,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse,Raptors 905
23,0,1610612762,1974,2019,UTA,Jazz,1974,Utah,Vivint Smart Home Arena,20148.0,Greg Miller,Dennis Lindsey,Quin Snyder,Salt Lake City Stars
24,0,1610612763,1995,2019,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle
25,0,1610612764,1961,2019,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
26,0,1610612765,1948,2019,DET,Pistons,1948,Detroit,Little Caesars Arena,21000.0,Tom Gores,Ed Stefanski,Dwane Casey,Grand Rapids Drive
27,0,1610612766,1988,2019,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,James Borrego,Greensboro Swarm
28,0,1610612739,1970,2019,CLE,Cavaliers,1970,Cleveland,Quicken Loans Arena,20562.0,Dan Gilbert,Koby Altman,John Beilein,Canton Charge
29,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors

In [66]:
maior_pontuacao_por_jogador = games_details.groupby('Nome do Jogador')['Pontos Feitos'].max().reset_index()
maior_pontuacao_por_jogador.columns = ['Nome do Jogador', 'Maior Pontuação']

In [67]:
top_50_maiores_pontuacoes = maior_pontuacao_por_jogador.sort_values(by='Maior Pontuação', ascending=False)

In [68]:
top_50_maiores_pontuacoes = top_50_maiores_pontuacoes.head(50)

In [69]:
print("Top 50 jogadores com as maiores pontuações em um único jogo:")
print(top_50_maiores_pontuacoes)

Top 50 jogadores com as maiores pontuações em um único jogo:
            Nome do Jogador  Maior Pontuação
1526            Kobe Bryant             81.0
672            Devin Booker             70.0
345         Carmelo Anthony             62.0
2340          Stephen Curry             62.0
2460          Tracy McGrady             62.0
515          Damian Lillard             61.0
1593           LeBron James             61.0
1095           James Harden             61.0
75            Allen Iverson             60.0
236            Bradley Beal             60.0
1187           Jayson Tatum             60.0
893          Gilbert Arenas             60.0
1524          Klay Thompson             60.0
1458           Kemba Walker             60.0
1431     Karl-Anthony Towns             60.0
1554           Kyrie Irving             60.0
129           Anthony Davis             59.0
1267            Joel Embiid             59.0
2207      Russell Westbrook             58.0
650          Deron Williams             57.0
1820           Michael Redd             57.0
714        Donovan Mitchell             57.0
1560      LaMarcus Aldridge             56.0
2462             Trae Young             56.0
610        DeMarcus Cousins             56.0
753             Dwyane Wade             55.0
253        Brandon Jennings             55.0
1226        Jermaine O'Neal             55.0
2450            Tony Parker             55.0
1489           Kevin Durant             55.0
848           Fred VanVleet             54.0
523        Damon Stoudamire             54.0
2099              Ray Allen             54.0
705           Dirk Nowitzki             53.0
1246           Jimmy Butler             53.0
987           Isaiah Thomas             53.0
2366            T.J. Warren             53.0
891   Giannis Antetokounmpo             52.0
1013              Ja Morant             52.0
1077         Jamal Crawford             52.0
1288              John Wall             52.0
259             Brandon Roy             52.0
486        D'Angelo Russell             52.0
1867            Mo Williams             52.0
609           DeMar DeRozan             52.0
2003          Pascal Siakam             52.0
99             Andre Miller             52.0
1514        Khris Middleton             51.0
1633            Luka Doncic             51.0
2122       Richard Hamilton             51.0

In [33]:
jogos_com_mais_de_55_pontos = games_details[games_details['Pontos Feitos'] > 54]

In [34]:
contagem_mais_de_55_pontos = jogos_com_mais_de_55_pontos['Nome do Jogador'].value_counts()

In [35]:
print("Número de vezes que cada jogador fez mais de 55 pontos em uma partida:")
print(contagem_mais_de_55_pontos)

Número de vezes que cada jogador fez mais de 55 pontos em uma partida:
Nome do Jogador
James Harden          11
Kobe Bryant            7
Damian Lillard         5
LeBron James           5
Kyrie Irving           3
Devin Booker           3
Bradley Beal           2
Stephen Curry          2
Karl-Anthony Towns     2
Anthony Davis          2
DeMarcus Cousins       2
Russell Westbrook      2
Joel Embiid            1
Kevin Durant           1
Donovan Mitchell       1
Jayson Tatum           1
Trae Young             1
Dwyane Wade            1
Michael Redd           1
Allen Iverson          1
Tony Parker            1
Gilbert Arenas         1
Tracy McGrady          1
Jermaine O'Neal        1
Deron Williams         1
Brandon Jennings       1
Kemba Walker           1
LaMarcus Aldridge      1
Klay Thompson          1
Carmelo Anthony        1
Name: count, dtype: int64

In [36]:
jogos_com_mais_de_10_bolas_3 = games_details[games_details['Três Pontos Convertidos'] > 9]

In [37]:
contagem_jogos_mais_de_10_bolas_3 = jogos_com_mais_de_10_bolas_3['Nome do Jogador'].value_counts()

In [38]:
print("Número de vezes que cada jogador acertou mais de 10 bolas de 3 pontos em uma partida:")
print(contagem_jogos_mais_de_10_bolas_3)

Número de vezes que cada jogador acertou mais de 10 bolas de 3 pontos em uma partida:
Nome do Jogador
Stephen Curry       22
Klay Thompson        7
Damian Lillard       6
James Harden         3
JR Smith             3
Zach LaVine          2
Saddiq Bey           1
Robert Covington     1
Darius Garland       1
Tyler Herro          1
Evan Fournier        1
Anthony Edwards      1
Kelly Oubre Jr.      1
Malik Beasley        1
Terry Rozier         1
Tim Hardaway Jr.     1
Danilo Gallinari     1
Jaylen Brown         1
Fred VanVleet        1
Marcus Smart         1
Duncan Robinson      1
Bojan Bogdanovic     1
Devonte' Graham      1
Peja Stojakovic      1
Donyell Marshall     1
Ty Lawson            1
Buddy Hield          1
Paul George          1
Kemba Walker         1
Wesley Matthews      1
Kyrie Irving         1
Trevor Ariza         1
Terrence Ross        1
Chandler Parsons     1
CJ Miles             1
Joe Johnson          1
Deron Williams       1
Mario Chalmers       1
Name: count, dtype: int64

In [45]:
jogadores_por_temporada = players.groupby('Temporada')['Código do Jogador'].nunique()

In [46]:
temporada_com_mais_jogadores = jogadores_por_temporada.idxmax()

In [47]:
numero_de_jogadores = jogadores_por_temporada.max()

In [48]:
jogadores_por_temporada = players.groupby('Temporada')['Código do Jogador'].nunique()

In [49]:
print("Número de jogadores por temporada:")
print(jogadores_por_temporada)

Número de jogadores por temporada:
Temporada
2009    514
2010    518
2011    528
2012    556
2013    554
2014    578
2015    596
2016    590
2017    626
2018    627
2019    618
Name: Código do Jogador, dtype: int64

In [50]:
print(f"A temporada com o maior número de jogadores foi: {temporada_com_mais_jogadores}")
print(f"Número de jogadores nessa temporada: {numero_de_jogadores}")

A temporada com o maior número de jogadores foi: 2018
Número de jogadores nessa temporada: 627

In [51]:
triple_doubles = games_details[
    (games_details['Pontos Feitos'] > 10) &
    (games_details['Assistências'] > 10) &
    (games_details['Rebotes'] > 10)
]

In [52]:
contagem_triple_doubles_por_jogador = triple_doubles['Nome do Jogador'].value_counts()

In [53]:
top_20_triple_doubles = contagem_triple_doubles_por_jogador.head(20)

In [54]:
print("Top 20 jogadores com mais partidas com Triplo-Duplo:")
print(top_20_triple_doubles)

Top 20 jogadores com mais partidas com Triplo-Duplo:
Nome do Jogador
Russell Westbrook        136
LeBron James              68
Nikola Jokic              42
James Harden              31
Luka Doncic               26
Jason Kidd                24
Rajon Rondo               19
Ben Simmons               18
Giannis Antetokounmpo     15
Draymond Green            14
Kyle Lowry                 7
Elfrid Payton              7
Kobe Bryant                6
Jimmy Butler               6
Chris Paul                 6
Domantas Sabonis           6
Pau Gasol                  6
Julius Randle              5
Dejounte Murray            5
Blake Griffin              5
Name: count, dtype: int64

In [56]:
lebron_id = players[players['Nome do Jogador'] == 'LeBron James']['Código do Jogador'].iloc[0]
curry_id = players[players['Nome do Jogador'] == 'Stephen Curry']['Código do Jogador'].iloc[0]

In [57]:
lebron_games = games_details[games_details['Código do Jogador'] == lebron_id]
curry_games = games_details[games_details['Código do Jogador'] == curry_id]

In [58]:
confronto_games_ids = lebron_games[lebron_games['Código do Jogo'].isin(curry_games['Código do Jogo'])]['Código do Jogo'].unique()

In [59]:
confronto_results = games[games['Código do Jogo'].isin(confronto_games_ids)]

In [60]:
vitorias_lebron = 0
vitorias_curry = 0

In [61]:
games.columns = ['Data do Jogo', 'Código do Jogo', 'Status do Jogo',
                 'Código do Time Casa', 'Código do Time Visitante', 'Temporada',
                 'Código do Time Mandante', 'Pontos do Mandante', 'Porcentagem de Arremesso do Mandante',
                 'Porcentagem de Lance Livre do Mandante', 'Porcentagem de Arremesso de 3 do Mandante',
                 'Assistência do Mandante', 'Rebotes do Mandante',
                 'Código do Time Visitante (Duplicado)', # Or a more accurate name if known
                 'Pontos do Visitante', 'Porcentagem de Arremesso do Visitante',
                 'Porcentagem de Lance Livre do Visitante', 'Porcentagem de Arremesso de 3 do Visitante',
                 'Assistência do Visitante', 'Rebotes do Visitante', 'Se o time mandante venceu']

In [62]:
for game_id in confronto_games_ids:
    # Encontrar os times que jogaram neste jogo
    game_info = games[games['Código do Jogo'] == game_id].iloc[0]
    time_mandante_id = game_info['Código do Time Casa']
    time_visitante_id = game_info['Código do Time Visitante']

    # Verificar qual time LeBron e Curry estavam neste jogo para o jogo atual
    lebron_in_game = games_details[(games_details['Código do Jogo'] == game_id) & (games_details['Código do Jogador'] == lebron_id)]
    curry_in_game = games_details[(games_details['Código do Jogo'] == game_id) & (games_details['Código do Jogador'] == curry_id)]

    # Precisamos garantir que ambos os jogadores participaram deste jogo antes de continuar
    if not lebron_in_game.empty and not curry_in_game.empty:
        lebron_time_id = lebron_in_game['Código do Time'].iloc[0]
        curry_time_id = curry_in_game['Código do Time'].iloc[0]

        # Get the winner of the game
        mandante_venceu = game_info['Se o time mandante venceu']

        # Contar as vitórias
        if mandante_venceu:
            if lebron_time_id == time_mandante_id:
                vitorias_lebron += 1
            elif curry_time_id == time_mandante_id:
                vitorias_curry += 1
        else: # Time visitante venceu
            if lebron_time_id == time_visitante_id:
                vitorias_lebron += 1
            elif curry_time_id == time_visitante_id:
                vitorias_curry += 1

In [63]:
print(f"Vitórias de LeBron James em confrontos diretos: {vitorias_lebron}")
print(f"Vitórias de Stephen Curry em confrontos diretos: {vitorias_curry}")

if vitorias_lebron > vitorias_curry:
    print("LeBron James tem mais vitórias em confrontos diretos.")
elif vitorias_curry > vitorias_lebron:
    print("Stephen Curry tem mais vitórias em confrontos diretos.")
else:
    print("LeBron James e Stephen Curry têm o mesmo número de vitórias em confrontos diretos.")

Vitórias de LeBron James em confrontos diretos: 25
Vitórias de Stephen Curry em confrontos diretos: 28
Stephen Curry tem mais vitórias em confrontos diretos.